# Generated by Django 4.2.1 on 2023-05-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.IntegerField(choices=[(1, 'Sdec'), (2, 'Yandex'), (3, 'Home')])),
                ('city', models.CharField(blank=True, max_length=30)),
                ('X', models.FloatField(blank=True)),
                ('Y', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
                ('lat', models.FloatField(blank=True)),
            ],
        ),
    ]
