# Generated by Django 4.2.1 on 2023-05-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoint',
            name='X',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='Y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
