# Generated by Django 4.2.1 on 2023-05-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0002_alter_deliverypoint_x_alter_deliverypoint_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoint',
            name='X',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='Y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
